### ISSUE TITLE
Have Leo self register with operating system (create menu links, icons, etc)

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1012]
There are some aging Leo scripts for setting file type associations etc. for Leo on Windows -- `register-leo.leox` and `un-register-leo.leox` under [`leo/scripts/`](https://github.com/leo-editor/leo-editor/tree/master/leo/scripts). They are designed to run from inside Leo with `Ctrl-B` or from command line `leo --script=...`. 

It would be good to upgrade these to include creating start menu links, deskop shortcuts with icons and so on. Ideally they would also work on Linux and Mac, and be activated from somewhere in the _Settings_ menu.

I'm confident I can do the Windows part but could use help on the others.

### Windows
- [x] Update register and unregister scripts to work with current Leo
- [x] (un)register from python as well as within Leo
- [x] Automatically prompt for User Account Control (UAC, permissions elevation) -- if can
- [x] <strike>Make python2 compatible (#1099)</strike>
- [x] Scripts for creating and removing Menu and Desktop links (#1243)
- [x] Document how to use (#1244)

### Linux: see #1246

# Current Status - Windows
_2019-07-30_
Integrated into Settings menu as _"Open Desktop Integration Leo"_, which creates two buttons in the menu bar, which carry out the actions described below. There's no logic to distinguish between OS yet, so the menu shows on Linux and Mac also.

_2019-02-27_  
Register and Unregister now work a) from Leo GUI, b) from Leo command line, and c) from straight python :-) 👍 

**Leo GUI:**
   - Run Leo >> Open specific Leo file >> `scripts.leo` >>  Find "Windows only scripts" node\* >> select **`@file win-register-leo.leox`** >> Execute script (Ctrl-B) 

   \* Current node location, subject to change: `.../leo-editor/leo/scripts/scripts.leo#Scripts-->@file leoScripts.txt-->Command-line scripts-->Windows-only scripts` 

**Leo script:**
`leo-messages.exe --script=..\scripts\win-register-leo.leox`

**Python:**
`python .\leo-editor\leo\scripts\win-register-leo.leox`

_--Script_ path must be relative to `leo-editor\leo\core` NOT the filesystem (a bug in Leo core I think).

**Comment by maphew** [comment]
Investigate `shortcutter` - https://github.com/kiwi0fruit/shortcutter - _Easy cross-platform creation of shortcuts supporting virtual and Anaconda environments_

**Comment by edreamleo** [comment]
On Sun, Nov 4, 2018 at 11:48 AM matt wilkie <notifications@github.com>
wrote:

> There are some aging Leo scripts for setting file type associations etc.
> for Leo on Windows -- register-leo.leox and un-register-leo.leox under
> leo/scripts/
> <https://github.com/leo-editor/leo-editor/tree/master/leo/scripts>. They
> are designed to run from inside Leo with Ctrl-B or from command line leo
> --script=....
>
> It would be good to upgrade these to include creating start menu links,
> deskop shortcuts with icons and so on.
>
I agree.

Edward

**Comment by maphew** [comment]
Part way there. I've adjusted `register-leo.leox` for py3 and fixed a unicode escape error. Next up is to relaunch the script with admin privileges. The relaunch attempt fires but fails because we don't have the path to script correct.

```
--- Running register-leo Leo script
Re-run the program with admin rights...
exception executing script
NameError: name '__file__' is not defined

--------------------
   line 122:     g.es("Re-run the program with admin rights...")
* line 123:     ctypes.windll.shell32.ShellExecuteW(None, "runas", sys.executable, __file__, None, 1)
   line 124: 
   line 125: 
```

**Comment by maphew** [comment]
Created branch `desktop-links` to keep maybe-not-working as well as possibly-dangerous scripts out of everyone else's way.

`__file__` not found was addressed by writing contents of `g.app.scriptDict['script2']` to a temp file. We then attempt to run that exported script with elevated permissions, but that block of the script isn't firing for some reason.

Side notes:
- `leo --script {path}` always creates a full path starting with `path\to\leo\core`, so you need to pass {path} relative to that (see next point). This is probably a bug.
- `g.app.scriptDict` doesn't get populated when run from command line with `leo ..\scripts\register-leo.leox`. It's only populated when run from inside Leo with `execute-script` (`[ctrl-b]`)

**Comment by maphew** [comment]
With today's work culminating in commit 5f3c5698 **win-register-leo** and **win-unregister-leo** scripts work again. After registration:

- `.leo` files use Leo's icon
- 2x-clicking `something.leo` launches Leo and opens that file

Example output when running as normal user:
```
--- Running register-leo Leo script
No admin privileges. Start Leo as administrator first and then run this script
--- end of script
```

And after starting as Administrator:
```
--- Running register-leo Leo script
Attempting to register leo filetype with Windows...
  Python: c:\apps\miniconda3\envs\leo-dev\pythonw.exe
  Leo: C:/Users/mattw/code/leo-editor/launchLeo.py
  Found: C:/Users/mattw/code/leo-editor/leo\Icons\LeoDoc.ico
  Registered!
  .leo, .leox files associated as 'Leo.File'
--- end of script
```
and
```
--- Running unregister-leo Leo script
  Attempting to un-register leo filetype with Windows...
  Leo file type has been removed from registry
  .leo, .leox file associations removed from registry
--- end of script
```

Caveats:

- Leo must be started as Administrator
- They must be run from a source checkout (so not from a pip install unless was installed with `--editable`. This is because the scripts assume `launchLeo.py` which doesn't exist outside of a source checkout.)
- They don't work as command line scripts, `leo --script leo\scripts\win-register-leo.leox`. They did a few years ago. I don't know why yet.

**Comment by edreamleo** [comment]
On Sat, Feb 16, 2019 at 5:24 PM matt wilkie <notifications@github.com>
wrote:

> With today's work culminating in commit 5f3c569
> <https://github.com/leo-editor/leo-editor/commit/5f3c5698d15a536a01654555ff741376ffc8c129>
> *win-register-leo* and *win-unregister-leo* scripts work again.
>

Many thanks for this.

Edward

**Comment by maphew** [comment]
With bb0e6bba incomplete works in progress and scrap is removed. 

I've rediscovered the `elevate.py` which I put there years ago and is better than all the similar crap I've been doing lately(!). All it needed was a unicode bug fix, though that one did take awhile to identify.

The (un)register scripts *do* work from the command line, but the command line needs to be crafted properly. I'll document that soon. I'm hoping to get a fully working "request elevation from inside Leo" recipe first.

Register now works for both source code checkout and pip installed Leo.

**Comment by maphew** [comment]
Register and Unregister now work a) from Leo GUI, b) from Leo command line, and c) from straight python :-) 👍 

**Python:**
`python .\leo-editor\leo\scripts\win-register-leo.leox`

**Leo script:**
`leo-messages.exe --script=..\scripts\win-register-leo.leox`

_--Script_ path must be relative to `leo-editor\leo\core` NOT the filesystem (a bug in Leo core I think).

**Leo GUI:**
   - Run Leo >> Open specific Leo file >> `scripts.leo` >>  Find "Windows only scripts" node\* >> select **`@file win-register-leo.leox`** >> Execute script (Ctrl-B) 

   \* Current node location, subject to change: `.../leo-editor/leo/scripts/scripts.leo#Scripts-->@file leoScripts.txt-->Command-line scripts-->Windows-only scripts` 

------
### Expected results
```
(leo-dev) matt@ENV-SURFACE-MHW C:\Users\mattw\code\leo-editor
> python leo\scripts\win-register-leo.leox
--- Running register-leo Leo script
No admin privileges. Start Leo as administrator first and then run this script 
--- end of script
```
```
matt@ENV-SURFACE-MHW C:\Users\mattw\code
$ c:\apps\miniconda3\envs\leo-dev\python leo-editor\leo\scripts\win-register-leo.leox
--- Running register-leo Leo script
Attempting to register leo filetype with Windows...
  Python: c:\apps\miniconda3\envs\leo-dev\pythonw.exe
  Leo: c:\apps\miniconda3\envs\leo-dev\Scripts\leo.exe
  Found: c:\users\mattw\code\leo-editor\leo\Icons\LeoDoc.ico
  Registered!
  .leo, .leox files associated as 'Leo.File'
--- end of script

matt@ENV-SURFACE-MHW C:\Users\mattw\code
$ c:\apps\miniconda3\envs\leo-dev\python leo-editor\leo\scripts\win-unregister-leo.leox
--- Running unregister-leo Leo script
  Attempting to un-register leo filetype with Windows...
  Leo file type has been removed from registry
  .leo, .leox file associations removed from registry
--- end of script

matt@ENV-SURFACE-MHW C:\Users\mattw\code
$ c:\apps\miniconda3\envs\leo-dev\Scripts\leo-m.exe --script=..\scripts\win-register-leo.leox

Leo 5.8.1-b2 devel, build 20190222005157, Fri Feb 22 00:51:57 PST 2019
--- Running register-leo Leo script
Attempting to register leo filetype with Windows...
  Python: c:\apps\miniconda3\envs\leo-dev\pythonw.exe
  Leo: c:\apps\miniconda3\envs\leo-dev\Scripts\leo.exe
  Found: c:\users\mattw\code\leo-editor\leo\Icons\LeoDoc.ico
  Registered!
  .leo, .leox files associated as 'Leo.File'
```

Remaining to-do before complete: Request elevation prompt when running from Leo gui.

**Comment by maphew** [comment]
pushed in commit b5017f610b6eb7b7839ac83fb7c9908a85f60c88

**Comment by maphew** [comment]
With b380d72 there's no longer a need to manually launch Leo or a command shell as administrator. Yay!

The prompt for elevation from just python on the command line does not work. I haven't dug into it because now that we can fire from inside Leo it's less necessary. There's room for refactoring: there are duplicate functions across the scripts in cross-file clones.

**Comment by maphew** [comment]
I created sub-issues removed Milestone marker for this parent one. So the components can have different milestones.

**Comment by maphew** [comment]
updated _current status_ note.

**Comment by maphew** [comment]
This is functionally complete for Windows and half there for Linux (lightly tested) so I'm going to close. I wish for a nicer looking way to describe and use the scripts but changing UI would be a much bigger project.
