### ISSUE TITLE
Checklist for 5.9.1

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1141]
5.9.1 will be released when all items here are complete.

- [x] Won't do: Back port leoflexx.py when #1127, #1131, and #1140 are complete.
  Flexx requires Python 3, so there is no reason to make it part of Leo 5.9.x.
- [x] Won't do: Back port removal of commit_timestamp.json:
  - Remove leo/core/hooks.
  - Update signon logic in leoApp.py.
  - Add g.getGitVersion.
  - Use simpler leoVersion.py.
  There is no reason to do this unless there are bugs **in the Python 2 code base**.
  At present, there are no such bugs.
- [x] Deal with nested `@clean`. Document its problems or remove it. See #1134.
  For now, it suffices simply to update Leo's web docs.
  Any real code changes can wait until Leo 6.0.

**Comment by edreamleo** [comment]
I am going to close this issue.  At present, there is no need for a 5.9.1 release.
