### ISSUE TITLE
python 2 remnants collection 

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1446]
This issue is to collect the stray functions here and there that come from py2, which are no longer needed now that py2 support is dropped. This issue isn't for discussion or bug reporting, just that such-n-such has been found. Create new child issues for extended info on specific items if that is needed.   
_-- https://groups.google.com/d/topic/leo-editor/ZLW85pIqW-0/discussion_

- [x] EKR: g.exec_file should remain. Indeed, execfile exists in python 2, but *not* python 3.
  Therefore, g.exec_file is *not* a python 2 remnant.
- [x] #1454: Remove 'python -Wd' warnings.
- [x] #1461: Retire the scripts_menu plugin.
- [x] #1642: Retire leoSAGlobals.py.

**Comment by edreamleo** [comment]
@maphew Good catch.  I'll delete this soon.

**Comment by edreamleo** [comment]
I am going to close this issue.  The -Wd warnings found a lot of cruft.  Please reopen if necessary.

**Comment by edreamleo** [comment]
I am going to reopen this issue because leoSAGlobals should be rewritten.

**Comment by edreamleo** [comment]
Recent revs complete all items.  Please reopen if/when new items appear.
