### ISSUE TITLE
Make calendars work in todo.py

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#1882]
todo.py uses plugins/QNCalendarWidget.py. This file mostly tests packing of calendar widgets into layouts. Imo, there is no need for this generality.

- [ ] Use callbacks, not wrapper classes, to associate calendars with popups.
- [ ] Remove QNCalendarWidget.py.
- [ ] If necessary, add unit tests to todo.py,
    activated as usual with a call to unittest.main.
