### ISSUE TITLE
Host Leo's web site using GitHub Pages.

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#3019]
This issue is a restart of issue #480. My brother Speed approves of the general plan.

No PR corresponds to this issue. See info item #3041 for the suggested workflow.

Moving Leo's website is worth doing, even if GitHub Pages were to disappear tomorrow:
- The `leo-editor/docs` directory shows explicitly what Leo's new website contains.
  This directory also contains a few transition files.
- The `@button find-bad-links` script in LeoDocs.leo is an excellent addition.
- Info item #3041 is long overdue.

**Summary of tasks**

- Update `index.html` in LeoDocs.leo.
- Change all links in LeoDocs.leo.
- Update `@button make-sphinx` in LeoDocs.leo.
- Create `@button find-bad-links` in LeoDocs.leo.
- Copy files from `leo/doc/html/_build/html` to `leo-editor/docs` as needed.
- Copy various folders to `leo-editor/docs`.

**Tasks**

- [x] Create a new website using [GitHub Pages](https://github.com/leo-editor/leo-editor/settings/pages), using a branch called `gh-pages`.
   `leo-editor/docs`  contains the files served to `https://leo-editor.github.io/leo-editor/`
   `leo-editor/docs/.nojekyll` allows the folder to contain Leo's static site, created by Sphinx.
- [x] Update Sphinx.
- [x] Generate `/docs/index.html` using `@file ../../docs/index.html` in LeoDocs.leo.
- [x] Announce the site! Expect [Leo 6.7.2](https://github.com/leo-editor/leo-editor/issues?q=is%3Aissue+milestone%3A6.7.2) on Friday, January 27 or later.
- [x] Create Info item #3041.
- [x] Change links in LeoDocs.leo.
- [x] Remove/fix failing link re flatter.com.
- [x] Debug the home page's search box. Make sure it returns results in the new website.
- [x] Fix the links in posts pinned to the top of [Leo's](http://leoeditor.com/) Google Group.
- [x] Create `@button find-bad-links` in LeoDocs.leo.
- [x] Create `redirect_index.html` using `@file ../../docs/redirect_index.html` in `LeoDocs.leo`.
- [x] Restore the screenshot in the new home page.
- [x] Change links in leoDist.leo.
- [x] Add load-leo.html to /docs.
- [x] Announce new links in Wikipedia and SourceForge.
- [x] Remove the word 'New' from the `index.html`.
- [x] Revise and test `@button make-sphinx` in `LeoDocs.leo`.
   For now, this `@button` node writes *all* intermediate files. Further improvements depend upon
   #3038.
- [x] Revise `@button find-bad-links` to use `glob.glob` to check all `.html` files in `leo-editor/docs`.
- [x] Fix broken links.
- [x] Upload a `redirect_index.html` (renamed to `index.html`) to `leoeditor.com` (Speed's server).
   This step will complete the changeover to the website.

**Notes**

- We won't transfer the `leo-editor.com` domain name.
  `leoeditor.com` will "wither away" when the domain name expires.
- There is no need for a script to move everything in `/doc/html/_build/html` to `/docs`

**Comment by edreamleo** [comment]
I am closing this issue:
- All tasks are complete and documented.
- `leoeditor.com/index.html` redirects visitors to `https://leo-editor.github.io/leo-editor/`.
