### ISSUE TITLE
Summary of tasks revealing/improving Leo's existing features

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#770]
Excerpted from [this post](https://groups.google.com/d/msg/leo-editor/scjyAiA-DXU/BGgYjU4iBAAJ):

- [ ] #760: Move python_console plugin into Leo's core
- [ ] #761: Make the valuespace plugin more visible
- [ ] #762: quickstart.leo & CheatSheet.leo should demo Leo's features, including markdown rendering.
- [ ] #764: Improve the screen shot on Leo's home page.
- [ ] #765: Improve the Cmds menu.
- [ ] #766: Create a Themes menu and simplify theme settings.
- [ ] #767: Add markdown command similar to rst3 command.
- [ ] #763: Use html comments to support @file x.md.

**Comment by edreamleo** [comment]
I have removed the First menu from this summary.  Individual items are labelled First.
