### ISSUE TITLE
Summary: Themes items

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#803]
- [x] #808 Loading Images in Themes is Broken.
- [x] #766: Create a Themes menu.
- [x] #790: Support @load-themes setting.
   Won't do: `@string theme-name` suffices.
